// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HomeFooter: typeof import('./src/components/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    MagicsHeader: typeof import('./src/components/MagicsHeader.vue')['default']
    MagicsProductCard: typeof import('./src/components/MagicsProductCard.vue')['default']
    MagicsProductListings: typeof import('./src/components/MagicsProductListings.vue')['default']
    MagicsProductPrice: typeof import('./src/components/MagicsProductPrice.vue')['default']
  }
}

export { }
